export enum Target {
  PATIENT= 'PATIENT' ,
  WOMAN = 'WOMAN',
  MAN = 'MAN',
  CHILDBEARING_AGE_WOMAN = 'CHILDBEARING_AGE_WOMAN',
  CHILDBEARING_AGE_MAN = 'CHILDBEARING_AGE_MAN',
  CHILD_LESS_5 = 'CHILD_LESS_5',
  CHILD_MORE_5 = 'CHILD_MORE_5',
  CHILD_LESS_1_MONTH = 'CHILD_LESS_1_MONTH',
  CHILD_LESS_2_MONTHS = 'CHILD_LESS_2_MONTHS',
  CHILD_LESS_24_MONTHS = 'CHILD_LESS_24_MONTHS',
  CHW = 'CHW',
  CHW_AREA = 'CHW_AREA',
  SV_AREA = 'SV_AREA',
  SM = 'SM'
}
